function names = appDefaultTestNames()
% APPDEFAULTTESTNAMES Return tests exposed in the App Designer Tests view.
%
% Author: Mohammed Ahmed
% Date: 2026
%
% Inputs:
%   None
%
% Outputs:
%   names (cell): Ordered list of test function names supported by
%                 app_test_runner.m.
%
% Example:
%   names = appDefaultTestNames();

names = { ...
    'test_config_loader', ...
    'test_survey_schema', ...
    'test_phase0_io', ...
    'test_phase1_feeder', ...
    'test_bfs_power_flow', ...
    'test_pq_indices', ...
    'test_simulate_occupancy', ...
    'test_simulate_household', ...
    'test_ev_model', ...
    'test_phase2_load_model', ...
    'test_pricing', ...
    'test_phase3_pricing', ...
    'test_milp', ...
    'test_phase4_dsm', ...
    'test_phase5_scenarios', ...
    'test_phase6_visualization', ...
    'test_phase7_household_twin', ...
    'test_phase8_tests_inventory', ...
    'test_phase9_main_export', ...
    'test_part_a_bug_fixes', ...
    'test_part_b_step9_ui_structure', ...
    'test_part_b_step10_app_skeleton', ...
    'test_part_b_step11_core_views', ...
    'test_part_b_step12_scenarios_view', ...
    'test_part_b_step13_results_view', ...
    'test_part_b_step14_export_view' ...
};
end
